config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'
  devise_for :coaches, controllers: { sessions: "coaches/sessions" }
  devise_for :users, controllers: { sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :coaches do
    resources :programs
    resources :avatar, only: [:create]
  end
  resources :coach_spheres, only: [:create, :destroy]
  resources :users
  resources :spheres
  resources :cities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :coaches
  has_one_attached :city_picture
end

app/models/coach.rb
class Coach < ApplicationRecord

  #validates :username, presence: true
  validates :email, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :city, optional: true
  has_many :coach_spheres
  has_many :spheres, through: :coach_spheres
  has_one_attached :avatar
end

app/models/coach_sphere.rb
class CoachSphere < ApplicationRecord
  belongs_to :coach
  belongs_to :sphere
  validates :sphere_id, :uniqueness => { :scope => :coach_id }
end

app/models/sphere.rb
class Sphere < ApplicationRecord
  has_many :coach_spheres
  has_many :coaches, through: :coach_spheres
  has_one_attached :sphere_picture
end

app/models/user.rb
class User < ApplicationRecord

  #validates :username, presence: true
  validates :email, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/avatar_controller.rb
class AvatarController < ApplicationController
  def create
    @coach = Coach.find(params[:coach_id])
    @coach.avatar.attach(params[:avatar]) if params[:avatar]
    redirect_to(coach_path(@coach))
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    
  end
  def show

  end

  def new

  end

  def edit

  end

  def create
  end

  def update

  end

  def destroy
    
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]
  before_action :is_coach, only: [:edit, :updtae, :new, :destroy]
  def index
    @coaches = Coach.all
  end
  
  def show

  end

  def new

  end

  def edit
    @spheres = Sphere.all.map{|s| [ s.name, s.id ] }
  end

  def create

  end

  def update
    set_coach_sphere
    if @coach.update(username: params[:username], description: params[:description], city: coach_city, subtitle: params[:subtitle], tariff: params[:tariff])
      redirect_to coach_path(@coach),  :notice => "Votre profil a bien été modifié."
    else
      redirect_back(fallback_location: coach_path(@coach))
    end
  end

  def destroy
    
  end

  private

  def set_coach
    @coach = Coach.find(params[:id])
  end

  def coach_city
    city = params[:city]
    if city == "" || city == nil
      return false
    elsif @coach.city && @coach.city.name.downcase == city.downcase
      return @coach.city
    else
      City.all.each do |old_city|
        if old_city.name.downcase == city.downcase
          return old_city
        end
      end
      return City.create(name: city.capitalize)
    end
  end

  def set_coach_sphere
    if params[:sphere_id] != "" && CoachSphere.create(coach: @coach, sphere_id: params[:sphere_id])
      return true
    end
  end

  def is_coach
    if !member_signed_in? || current_member != @coach
      redirect_to root_path, alert: "Accès non autorisé"
    end
  end
  
end

app/controllers/spheres_controller.rb
class SpheresController < ApplicationController
  before_action :set_sphere, only: [:show, :edit, :update, :destroy]

  def index
    
  end
  def show
    @coaches = @sphere.coaches
  end

  def new

  end

  def edit

  end

  def create
  end

  def update

  end

  def destroy
    
  end

  private 

  def set_sphere
    @sphere = Sphere.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @coaches = Coach.all
    @spheres = Sphere.all
    @cities = City.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    
  end

  def show

  end

  def new

  end

  def edit

  end

  def create
  end

  def update

  end

  def destroy
    
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/coach_spheres_helper.rb
module CoachSpheresHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/profil_picture_helper.rb
module ProfilPictureHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/spheres_helper.rb
module SpheresHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/index.html.erb
  <div class="jumbotron jumbotron-fluid" >
    <div class="container">
      <h1 class="display-4">Les meilleurs coachs personnels proches de chez vous</h1>
      <div class="row">
        <form class="form-inline">
          <input class="form-control mr-sm-2 search" type="search" placeholder="Domaine" aria-label="Search">
          <input class="form-control mr-sm-2 search" type="search" placeholder="Pays, Ville, Région,..." aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0 valid-search" type="submit">Rechercher</button>
        </form>
      </div>
    </div>
  </div>
 
  <h1>Trouvez le coach qu'il vous faut</h1>
  <div class="reasons_bloc">
    <div class="listing">
      <i class="fas fa-bullseye fa-3x "></i>
      <p>Faites votre choix parmis nos profils vérifiés
      </p>
      <i class="fas fa-bullseye fa-3x "></i>
      <p>Etablissez votre programme personnalisé ensemble
      </p>
      <i class="fas fa-bullseye fa-3x "></i>
      <p>Pratiquez où vous voulez, chez vous ou dans nos infrastructures partenaires
      </p>
    </div>

  <div class="section_title">
    <div><h1>Les spécialités les plus recherchées</h1></div>
    <div><a href="#"><i class="fas fa-arrow-circle-right fa-2x"></i></a></div>
  </div>
  <div class = "best_search">
    <% @spheres.each do |sphere|%>
      <div class="card <%=sphere.name%>" style="width: 18rem; height: 300px; background: url(<%= rails_blob_url(sphere.sphere_picture) %>); background-size: cover">
        <div class="card-body">
          <h5 class="card-title"><%= sphere.name%></h5>
          <%= link_to "<pan class='btn btn-success'>Découvrir</span>".html_safe, sphere_path(sphere)%>
        </div>
      </div>
    <% end %>
  </div>

  <div class="section_title">
  <div><h1>Des Coachs proches de vous</h1></div>
  <div>
    <a href="#"><i class="fas fa-arrow-circle-right fa-2x"></i></a></div>
  </div>
  <div class="regions">
  <% @cities.each do |city|%>
  <div class="card <%=city.name%>" style="width: 18rem; height: 300px; background: url(<%= rails_blob_url(city.city_picture) %>); background-size: cover">
    <%= link_to "<div class='card-body'><h5 class='card-title'>#{city.name}</h5></div>".html_safe, city_path(city)%>
  </div>
  <% end %>
  </div>