config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'
  devise_for :coaches, controllers: { sessions: "coaches/sessions" }
  devise_for :users, controllers: { sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :coaches do
    resources :programs
    resources :avatar, only: [:create]
  end
  resources :coach_spheres, only: [:create, :destroy]
  resources :users
  resources :spheres
  resources :cities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :coaches
  has_one_attached :city_picture
end

app/models/coach.rb
class Coach < ApplicationRecord

  #validates :username, presence: true
  validates :email, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :city, optional: true
  has_many :coach_spheres
  has_many :spheres, through: :coach_spheres
  has_one_attached :avatar
end

app/models/coach_sphere.rb
class CoachSphere < ApplicationRecord
  belongs_to :coach
  belongs_to :sphere
  validates :sphere_id, :uniqueness => { :scope => :coach_id }
end

app/models/sphere.rb
class Sphere < ApplicationRecord
  has_many :coach_spheres
  has_many :coaches, through: :coach_spheres
  has_one_attached :sphere_picture
end

app/models/user.rb
class User < ApplicationRecord

  #validates :username, presence: true
  validates :email, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/avatar_controller.rb
class AvatarController < ApplicationController
  def create
    @coach = Coach.find(params[:coach_id])
    @coach.avatar.attach(params[:avatar]) if params[:avatar]
    redirect_to(coach_path(@coach))
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    
  end
  def show

  end

  def new

  end

  def edit

  end

  def create
  end

  def update

  end

  def destroy
    
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]
  before_action :is_coach, only: [:edit, :updtae, :new, :destroy]
  def index
    @coaches = Coach.all
  end
  
  def show

  end

  def new

  end

  def edit
    @spheres = Sphere.all.map{|s| [ s.name, s.id ] }
  end

  def create

  end

  def update
    set_coach_sphere
    if @coach.update(username: params[:username], description: params[:description], city: coach_city, subtitle: params[:subtitle], tariff: params[:tariff])
      redirect_to coach_path(@coach),  :notice => "Votre profil a bien été modifié."
    else
      redirect_back(fallback_location: coach_path(@coach))
    end
  end

  def destroy
    
  end

  private

  def set_coach
    @coach = Coach.find(params[:id])
  end

  def coach_city
    city = params[:city]
    if city == "" || city == nil
      return false
    elsif @coach.city && @coach.city.name.downcase == city.downcase
      return @coach.city
    else
      City.all.each do |old_city|
        if old_city.name.downcase == city.downcase
          return old_city
        end
      end
      return City.create(name: city.capitalize)
    end
  end

  def set_coach_sphere
    if params[:sphere_id] != "" && CoachSphere.create(coach: @coach, sphere_id: params[:sphere_id])
      return true
    end
  end

  def is_coach
    if !member_signed_in? || current_member != @coach
      redirect_to root_path, alert: "Accès non autorisé"
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    
  end

  def show

  end

  def new

  end

  def edit

  end

  def create
  end

  def update

  end

  def destroy
    
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/coach_spheres_helper.rb
module CoachSpheresHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/profil_picture_helper.rb
module ProfilPictureHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/spheres_helper.rb
module SpheresHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThecoachApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Font Awesone
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script src="https://kit.fontawesome.com/82b59b489d.js" crossorigin="anonymous"></script>


  </head>

  <body>
    <%= render "shared/navbar"%>
      <% if !flash.alert.nil? %>
    <div class="mt-4 row">
    <div class="col-md-4"></div>
    <div class="col-md-4 text-center mt-3">
      <div class="alert alert-danger alert-dismissible" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%=  flash.alert %>
      </div>
    </div>
    </div>
    <% elsif !flash.notice.nil? %>
    <div class="mt-4 row">
    <div class="col-md-4"></div>
    <div class="col-md-4 text-center mt-3">
      <div class="alert alert-success alert-dismissible" role="alert">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%=  flash.notice %>
      </div>
    </div>
    </div>
    <% end %>
    <div class ="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-success">
  <h1><%= link_to 'TheCoach', root_path, class: "navbar-text-white"%></h1>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if current_coach%>
      <li class="nav-item">
        <%= link_to 'Profil', coach_path(current_coach), class: "nav-link navbar-text-white"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Se déconnecter', destroy_coach_session_path, method: :delete, class: "nav-link navbar-text-white"%>
      </li>
      <% elsif current_user%>
      <li class="nav-item">
        <%= link_to 'Profil', user_path(current_user), class: "nav-link navbar-text-white"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Se déconnecter', destroy_coach_session_path, method: :delete, class: "nav-link navbar-text-white"%>
      </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Se connecter", new_user_session_path, class:"navbar-text-white" %>
        </li>
        <li class="nav-item active">
          <%= link_to "S'inscrire", new_user_registration_path, class:"navbar-text-white" %>
        </li>
        <li class="nav-item dropdown ">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Je suis Coach
            </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Se connecter', new_coach_session_path, class: "dropdown-item"%>
            <%= link_to 'S\'inscrire', new_coach_registration_path, class: "dropdown-item"%>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>