config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'
  devise_for :coaches, controllers: { sessions: "coaches/sessions" }
  devise_for :users, controllers: { sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :coaches do
    resources :programs
    resources :avatar, only: [:create]
  end
  resources :coach_spheres, only: [:create, :destroy]
  resources :users
  resources :spheres
  resources :cities
end

app/models/coach.rb
class Coach < ApplicationRecord

  #validates :username, presence: true
  validates :email, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :city, optional: true
  has_many :coach_spheres
  has_many :spheres, through: :coach_spheres
  has_one_attached :avatar
end

app/controllers/coaches/confirmations_controller.rb
# frozen_string_literal: true

class Coaches::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/coaches/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Coaches::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/coaches/passwords_controller.rb
# frozen_string_literal: true

class Coaches::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/coaches/registrations_controller.rb
# frozen_string_literal: true

class Coaches::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/coaches/sessions_controller.rb
# frozen_string_literal: true

class Coaches::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/coaches/unlocks_controller.rb
# frozen_string_literal: true

class Coaches::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :update, :destroy]
  before_action :is_coach, only: [:edit, :updtae, :new, :destroy]
  def index
    @coaches = Coach.all
  end
  
  def show

  end

  def new

  end

  def edit
    @spheres = Sphere.all.map{|s| [ s.name, s.id ] }
  end

  def create

  end

  def update
    set_coach_sphere
    if @coach.update(username: params[:username], description: params[:description], city: coach_city, subtitle: params[:subtitle], tariff: params[:tariff])
      redirect_to coach_path(@coach),  :notice => "Votre profil a bien été modifié."
    else
      redirect_back(fallback_location: coach_path(@coach))
    end
  end

  def destroy
    
  end

  private

  def set_coach
    @coach = Coach.find(params[:id])
  end

  def coach_city
    city = params[:city]
    if city == "" || city == nil
      return false
    elsif @coach.city && @coach.city.name.downcase == city.downcase
      return @coach.city
    else
      City.all.each do |old_city|
        if old_city.name.downcase == city.downcase
          return old_city
        end
      end
      return City.create(name: city.capitalize)
    end
  end

  def set_coach_sphere
    if params[:sphere_id] != "" && CoachSphere.create(coach: @coach, sphere_id: params[:sphere_id])
      return true
    end
  end

  def is_coach
    if !member_signed_in? || current_member != @coach
      redirect_to root_path, alert: "Accès non autorisé"
    end
  end
  
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/views/coaches/_editFormCoach.html.erb
<%= form_tag coach_path, method: "put" do%>
  <h1 class="h3 mb-3 font-weight-normal text-center">Modifier mon profil</h1>
  <div class="form-group">
    <%= label_tag 'Username' %>
    <%= text_field_tag 'username', @coach.username, class: 'form-control' %>
  </div>
  <br /> <br />
  <div class="form-group">
    <%= label_tag 'Profession' %>
    <%= text_field_tag 'subtitle', @coach.subtitle, class: 'form-control', :maxlength => 50 %>
  </div>
  <br /> <br />
  <div class="form-group">
    <%= label_tag 'Description' %>
    <%= text_field_tag 'description', @coach.description, class: 'form-control' %>
  </div>
  <br /> <br />
  <% if !@coach.city %>
  <div class="form-group">
    <%= label_tag 'Ville' %>
    <%= text_field_tag 'city', "", class: 'form-control' %>
  </div>
  <% else %>
  <div class="form-group">
    <%= label_tag 'Ville' %>
    <%= text_field_tag 'city', @coach.city.name, class: 'form-control' %>
  </div>
  <% end %>
  <br /> <br />
  <div class="form-group">
      <%= label_tag 'Domaine' %>
      <%= select_tag 'sphere_id', options_for_select(@spheres), prompt: "Sélectionner une catégorie", class:"u-full-width" %>
  </div>
  <br /> <br />
  <div class="form-group">
    <%= label_tag 'Tarif horaire' %>
    <%= number_field_tag 'tariff', @coach.tariff, class: 'form-control'%>
  </div>
  <br /> <br />
  <div class="form-actions">
      <%= submit_tag "Modifier mon Profil", class: "btn btn-success" %>
  </div>
<% end %>
<% if @coach.errors.any? %>
  <div class="alert alert-danger" role="alert">
  <p>Nous n'avons pas réussi à modifier votre profil pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @coach.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

app/views/coaches/_showCoachProfil.html.erb
<h1>Hello <%= @coach.username%></h1>
<%if @coach.avatar.attached?%>
  <%= image_tag @coach.avatar, alt: 'avatar' %>
<%else%>
  <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
<%end%>
<%= form_tag coach_avatar_index_path(@coach), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "mettre à jour" %>
<% end %>
  <h2>Infos personnelles</h2>
  <ul>
    <li><%= @coach.email%></li>
    <li><%= @coach.description%></li>
    <% if @coach.city %>
      <li><%= @coach.city.name%></li>
    <% else %>
      <li>Pas de localisation renseignée</li>
    <% end %>
  </ul>
  <h2>Spheres</h2>
  <ul>
    <%@coach.spheres.each do |sphere|%>
      <li><%=sphere.name%> <%= link_to "a", coach_sphere_path(CoachSphere.find_by(coach: @coach, sphere: sphere).id), method: :delete, class: "close"%> </li>
    <% end %>
  </ul>

  <% if current_member == @coach %>
    <p>Pour pouvoir etre visible sur notre plateforme, vous devez completer votre profil !
    <%= link_to "Modifier mon profil ", edit_coach_path(@coach)%></p>
    <p>Modifier les infos du compte
    <%= link_to 'Paramètres du compte',edit_coach_registration_path, class:'button' %></p>
  <% end %>

app/views/coaches/_showCoachProfilForUsers.html.erb
<div class = "row", style = "justify-content: space-between; margin-top: 10px">
<%if @coach.avatar.attached?%>
  <%= image_tag @coach.avatar, alt: 'avatar', class: "avatar-circular col " %>
<%else%>
  <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
<%end%>
<div class = "col">
  <h2><%= @coach.username%></h2>
  <h4><%= @coach.subtitle%></h4>
  <p><i class="fas fa-map-marker-alt text-success"></i> <%=@coach.city.name%></p>
  <span class = "btn btn-info">
  <p class = "font-weight-light">Tarif indicatif</p><p class = "font-weight-bold"><%=@coach.tariff%>/heure</p>
  </span>
</div>
<div class = "col">
  <%= mail_to @coach.email, "Contacter", class: "btn btn-success", style: "width: 100%" %>
</div>
</div>

app/views/coaches/edit.html.erb
<%= render 'editFormCoach'%>

app/views/coaches/show.html.erb
<% if current_member == @coach %>
  <%= render 'showCoachProfil'%>
<% else %>
  <%= render 'showCoachProfilForUsers'%>
<% end %>